# Site settings
title: Hello, Adilson here ;D
description: Adilson Vital Junior Personal Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adilson Vital
user_description: Alchemy apprentice, enthusiastic about machine learning and curious about the world. Love teaching math and science to my little sister. Feel free to contact me =)
user_title: PhD Student in Artificial Intelligence
email: adilson.vital@usp.br
twitter_username: lorem_ipsum
github_username:  adilsonvj
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
